trigger:
  branches:
    include:
    - master

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly midnight (UTC) build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: | 
    git clone https://github.com/master-of-servers/puppet-test-lab.git
    cd puppet-test-lab && cd basic
    docker-compose up -d --build
    sleep 40
    # Enroll agent with puppet master
    docker exec -i basic-puppetagent /bin/bash -c "puppet agent -t --waitforcert=120"
    docker ps
  displayName: 'Build and configure the basic puppet test environment'

- script: | 
    docker-compose down -v
  displayName: 'Tear down the basic puppet test environment'
  workingDirectory: puppet-test-lab/basic

- script: | 
    cd puppet-test-lab && cd extended
    docker-compose up -d --build
    sleep 40
    # Enroll agent with puppet master
    docker exec -i extended-puppetagent /bin/bash -c "puppet agent -t --waitforcert=120"
    docker ps
  displayName: 'Build and configure the extended puppet test environment'

- script: | 
    docker-compose down -v
  displayName: 'Tear down the extended puppet test environment'
  workingDirectory: puppet-test-lab/extended